config/routes.rb
Rails.application.routes.draw do
  resources :urls
  root :to => redirect('/urls/new')

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/url.rb
class Url < ApplicationRecord
  validates :original, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  # before_action :set_url, only: [:show, :edit, :update, :destroy]

  def index
    @urls = Url.all
  end 

  def show
    url = Url.where(:short => params[:id]).first
    if url
      redirect_to url.original
    else
      render "index"
    end
  end 

  def new
    @url = Url.new
    letters = [('a'..'z'), ('A'..'Z')].map {|i| i.to_a}.flatten
    @url.short = (0...8).map{ letters[rand(letters.length)]}.join
  end

  def urls_params
    params.require(:url).permit(:original, :short)
  end 

  def create
    @url = Url.new(urls_params)
    if @url.save
      redirect_to urls_path
    else 
      render "new"
    end 
  end 

private
  def url_params
    params.require(:url).permit(:original, :short)
  end 
  
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UrlShorty</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/urls/index.html.erb
<h1>URL Shorty</h1>

<% @urls.each do |url| %>
<p>
  <%= link_to url.short, url_path(:id => url.short) %> => <%= url.original  %>
</p>
<% end %>

<%= link_to "New URL", new_url_path  %>

app/views/urls/new.html.erb
<h1>Shorten Here</h1>

<% @url.errors.each do |attr, msg| %>
<%= msg %> on <%= attr %>
<% end %>

<%= form_for @url do |f| %>

<p><%= f.label :original %> : <%= f.text_field :original %></p>

<p>
  <%= f.hidden_field :short, :value => @url.short %>
  <%= f.submit "Shorten" %>
</p>

<% end %>